// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ContentSynchronisationInitParameters struct {

	// If set, Remote repository proxies a local or remote repository from another instance of Artifactory. Default value is 'false'.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// If set, properties for artifacts that have been cached in this repository will be updated if they are modified in the artifact hosted at the remote Artifactory instance. The trigger to synchronize the properties is download of the artifact from the remote repository cache of the local Artifactory instance. Default value is 'false'.
	PropertiesEnabled *bool `json:"propertiesEnabled,omitempty" tf:"properties_enabled,omitempty"`

	// If set, Artifactory displays an indication on cached items if they have been deleted from the corresponding repository in the remote Artifactory instance. Default value is 'false'
	SourceOriginAbsenceDetection *bool `json:"sourceOriginAbsenceDetection,omitempty" tf:"source_origin_absence_detection,omitempty"`

	// If set, Artifactory will notify the remote instance whenever an artifact in the Smart Remote Repository is downloaded locally so that it can update its download counter. Note that if this option is not set, there may be a discrepancy between the number of artifacts reported to have been downloaded in the different Artifactory instances of the proxy chain. Default value is 'false'.
	StatisticsEnabled *bool `json:"statisticsEnabled,omitempty" tf:"statistics_enabled,omitempty"`
}

type ContentSynchronisationObservation struct {

	// If set, Remote repository proxies a local or remote repository from another instance of Artifactory. Default value is 'false'.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// If set, properties for artifacts that have been cached in this repository will be updated if they are modified in the artifact hosted at the remote Artifactory instance. The trigger to synchronize the properties is download of the artifact from the remote repository cache of the local Artifactory instance. Default value is 'false'.
	PropertiesEnabled *bool `json:"propertiesEnabled,omitempty" tf:"properties_enabled,omitempty"`

	// If set, Artifactory displays an indication on cached items if they have been deleted from the corresponding repository in the remote Artifactory instance. Default value is 'false'
	SourceOriginAbsenceDetection *bool `json:"sourceOriginAbsenceDetection,omitempty" tf:"source_origin_absence_detection,omitempty"`

	// If set, Artifactory will notify the remote instance whenever an artifact in the Smart Remote Repository is downloaded locally so that it can update its download counter. Note that if this option is not set, there may be a discrepancy between the number of artifacts reported to have been downloaded in the different Artifactory instances of the proxy chain. Default value is 'false'.
	StatisticsEnabled *bool `json:"statisticsEnabled,omitempty" tf:"statistics_enabled,omitempty"`
}

type ContentSynchronisationParameters struct {

	// If set, Remote repository proxies a local or remote repository from another instance of Artifactory. Default value is 'false'.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// If set, properties for artifacts that have been cached in this repository will be updated if they are modified in the artifact hosted at the remote Artifactory instance. The trigger to synchronize the properties is download of the artifact from the remote repository cache of the local Artifactory instance. Default value is 'false'.
	// +kubebuilder:validation:Optional
	PropertiesEnabled *bool `json:"propertiesEnabled,omitempty" tf:"properties_enabled,omitempty"`

	// If set, Artifactory displays an indication on cached items if they have been deleted from the corresponding repository in the remote Artifactory instance. Default value is 'false'
	// +kubebuilder:validation:Optional
	SourceOriginAbsenceDetection *bool `json:"sourceOriginAbsenceDetection,omitempty" tf:"source_origin_absence_detection,omitempty"`

	// If set, Artifactory will notify the remote instance whenever an artifact in the Smart Remote Repository is downloaded locally so that it can update its download counter. Note that if this option is not set, there may be a discrepancy between the number of artifacts reported to have been downloaded in the different Artifactory instances of the proxy chain. Default value is 'false'.
	// +kubebuilder:validation:Optional
	StatisticsEnabled *bool `json:"statisticsEnabled,omitempty" tf:"statistics_enabled,omitempty"`
}

type RemoteNpmRepositoryInitParameters struct {

	// 'Lenient Host Authentication' in the UI. Allow credentials of this repository to be used on requests redirected to any other host.
	AllowAnyHostAuth *bool `json:"allowAnyHostAuth,omitempty" tf:"allow_any_host_auth,omitempty"`

	// When set, you may view content such as HTML or Javadoc files directly from Artifactory.
	// This may not be safe and therefore requires strict content moderation to prevent malicious users from uploading content that may compromise security (e.g., cross-site scripting attacks).
	ArchiveBrowsingEnabled *bool `json:"archiveBrowsingEnabled,omitempty" tf:"archive_browsing_enabled,omitempty"`

	// The number of seconds the repository stays in assumed offline state after a connection error. At the end of this time, an online check is attempted in order to reset the offline status. A value of 0 means the repository is never assumed offline.
	AssumedOfflinePeriodSecs *float64 `json:"assumedOfflinePeriodSecs,omitempty" tf:"assumed_offline_period_secs,omitempty"`

	// (A.K.A 'Ignore Repository' on the UI) When set, the repository or its local cache do not participate in artifact resolution.
	BlackedOut *bool `json:"blackedOut,omitempty" tf:"blacked_out,omitempty"`

	// If set, artifacts will fail to download if a mismatch is detected between requested and received mimetype, according to the list specified in the system properties file under blockedMismatchingMimeTypes. You can override by adding mimetypes to the override list 'mismatching_mime_types_override_list'.
	BlockMismatchingMimeTypes *bool `json:"blockMismatchingMimeTypes,omitempty" tf:"block_mismatching_mime_types,omitempty"`

	// Before caching an artifact, Artifactory first sends a HEAD request to the remote resource. In some remote resources, HEAD requests are disallowed and therefore rejected, even though downloading the artifact is allowed. When checked, Artifactory will bypass the HEAD request and cache the artifact directly using a GET request.
	BypassHeadRequests *bool `json:"bypassHeadRequests,omitempty" tf:"bypass_head_requests,omitempty"`

	// When set, download requests to this repository will redirect the client to download the artifact directly from AWS CloudFront. Available in Enterprise+ and Edge licenses only. Default value is 'false'
	CdnRedirect *bool `json:"cdnRedirect,omitempty" tf:"cdn_redirect,omitempty"`

	// Client TLS certificate name.
	ClientTLSCertificate *string `json:"clientTlsCertificate,omitempty" tf:"client_tls_certificate,omitempty"`

	ContentSynchronisation []ContentSynchronisationInitParameters `json:"contentSynchronisation,omitempty" tf:"content_synchronisation,omitempty"`

	// Enable repository to be protected by the Curation service.
	Curated *bool `json:"curated,omitempty" tf:"curated,omitempty"`

	// Public description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// When set to `true`, the proxy is disabled, and not returned in the API response body. If there is a default proxy set for the Artifactory instance, it will be ignored, too. Introduced since Artifactory 7.41.7.
	DisableProxy *bool `json:"disableProxy,omitempty" tf:"disable_proxy,omitempty"`

	// Whether to disable URL normalization, default is `false`.
	DisableURLNormalization *bool `json:"disableUrlNormalization,omitempty" tf:"disable_url_normalization,omitempty"`

	// When set, download requests to this repository will redirect the client to download the artifact directly from the cloud storage provider. Available in Enterprise+ and Edge licenses only. Default value is 'false'.
	DownloadDirect *bool `json:"downloadDirect,omitempty" tf:"download_direct,omitempty"`

	// Enables cookie management if the remote repository uses cookies to manage client state.
	EnableCookieManagement *bool `json:"enableCookieManagement,omitempty" tf:"enable_cookie_management,omitempty"`

	// List of artifact patterns to exclude when evaluating artifact requests, in the form of `x/y/**/z/*`.By default no artifacts are excluded.
	ExcludesPattern *string `json:"excludesPattern,omitempty" tf:"excludes_pattern,omitempty"`

	// When set, Artifactory will return an error to the client that causes the build to fail if there is a failure to communicate with this repository.
	HardFail *bool `json:"hardFail,omitempty" tf:"hard_fail,omitempty"`

	// List of comma-separated artifact patterns to include when evaluating artifact requests in the form of `x/y/**/z/*`. When used, only artifacts matching one of the include patterns are served. By default, all artifacts are included (`**/*`).
	IncludesPattern *string `json:"includesPattern,omitempty" tf:"includes_pattern,omitempty"`

	// Lists the items of remote folders in simple and list browsing. The remote content is cached according to the value of the 'Retrieval Cache Period'. Default value is 'false'. This field exists in the API but not in the UI.
	ListRemoteFolderItems *bool `json:"listRemoteFolderItems,omitempty" tf:"list_remote_folder_items,omitempty"`

	// The local address to be used when creating connections. Useful for specifying the interface to use on systems with multiple network interfaces.
	LocalAddress *string `json:"localAddress,omitempty" tf:"local_address,omitempty"`

	// Metadata Retrieval Cache Timeout (Sec) in the UI.This value refers to the number of seconds to wait for retrieval from the remote before serving locally cached artifact or fail the request.
	MetadataRetrievalTimeoutSecs *float64 `json:"metadataRetrievalTimeoutSecs,omitempty" tf:"metadata_retrieval_timeout_secs,omitempty"`

	// The set of mime types that should override the block_mismatching_mime_types setting. Eg: 'application/json,application/xml'. Default value is empty.
	MismatchingMimeTypesOverrideList *string `json:"mismatchingMimeTypesOverrideList,omitempty" tf:"mismatching_mime_types_override_list,omitempty"`

	// Missed Retrieval Cache Period (Sec) in the UI. The number of seconds to cache artifact retrieval misses (artifact not found). A value of 0 indicates no caching.
	MissedCachePeriodSeconds *float64 `json:"missedCachePeriodSeconds,omitempty" tf:"missed_cache_period_seconds,omitempty"`

	// Internal description.
	Notes *string `json:"notes,omitempty" tf:"notes,omitempty"`

	// If set, Artifactory does not try to fetch remote artifacts. Only locally-cached artifacts are retrieved.
	Offline *bool `json:"offline,omitempty" tf:"offline,omitempty"`

	PasswordSecretRef *v1.SecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// Setting Priority Resolution takes precedence over the resolution order when resolving virtual repositories. Setting repositories with priority will cause metadata to be merged only from repositories set with a priority. If a package is not found in those repositories, Artifactory will merge from repositories marked as non-priority.
	PriorityResolution *bool `json:"priorityResolution,omitempty" tf:"priority_resolution,omitempty"`

	// Project environment for assigning this repository to. Allow values: "DEV", "PROD", or one of custom environment. Before Artifactory 7.53.1, up to 2 values ("DEV" and "PROD") are allowed. From 7.53.1 onward, only one value is allowed. The attribute should only be used if the repository is already assigned to the existing project.
	// +listType=set
	ProjectEnvironments []*string `json:"projectEnvironments,omitempty" tf:"project_environments,omitempty"`

	// Project key for assigning this repository to. Must be 2 - 32 lowercase alphanumeric and hyphen characters. When assigning repository to a project, repository key must be prefixed with project key, separated by a dash.
	ProjectKey *string `json:"projectKey,omitempty" tf:"project_key,omitempty"`

	// List of property set names
	// +listType=set
	PropertySets []*string `json:"propertySets,omitempty" tf:"property_sets,omitempty"`

	// Proxy key from Artifactory Proxies settings. Can't be set if `disable_proxy = true`.
	Proxy *string `json:"proxy,omitempty" tf:"proxy,omitempty"`

	// Custom HTTP query parameters that will be automatically included in all remote resource requests. For example: `param1=val1&param2=val2&param3=val3`
	QueryParams *string `json:"queryParams,omitempty" tf:"query_params,omitempty"`

	// Repository layout key for the remote layout mapping. Repository can be created without this attribute (or set to an empty string). Once it's set, it can't be removed by passing an empty string or removing the attribute, that will be ignored by the Artifactory API. UI shows an error message, if the user tries to remove the value.
	RemoteRepoLayoutRef *string `json:"remoteRepoLayoutRef,omitempty" tf:"remote_repo_layout_ref,omitempty"`

	// Repository layout key for the remote repository
	RepoLayoutRef *string `json:"repoLayoutRef,omitempty" tf:"repo_layout_ref,omitempty"`

	// Metadata Retrieval Cache Period (Sec) in the UI. This value refers to the number of seconds to cache metadata files before checking for newer versions on remote server. A value of 0 indicates no caching.
	RetrievalCachePeriodSeconds *float64 `json:"retrievalCachePeriodSeconds,omitempty" tf:"retrieval_cache_period_seconds,omitempty"`

	ShareConfiguration *bool `json:"shareConfiguration,omitempty" tf:"share_configuration,omitempty"`

	// Network timeout (in ms) to use when establishing a connection and for unanswered requests. Timing out on a network operation is considered a retrieval failure.
	SocketTimeoutMillis *float64 `json:"socketTimeoutMillis,omitempty" tf:"socket_timeout_millis,omitempty"`

	// When set, the repository should store cached artifacts locally. When not set, artifacts are not stored locally, and direct repository-to-client streaming is used. This can be useful for multi-server setups over a high-speed LAN, with one Artifactory caching certain data on central storage, and streaming it directly to satellite pass-though Artifactory servers.
	StoreArtifactsLocally *bool `json:"storeArtifactsLocally,omitempty" tf:"store_artifacts_locally,omitempty"`

	// When set, remote artifacts are fetched along with their properties.
	SynchronizeProperties *bool `json:"synchronizeProperties,omitempty" tf:"synchronize_properties,omitempty"`

	// This is a URL to the remote registry. Consider using HTTPS to ensure a secure connection.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// Unused Artifacts Cleanup Period (Hr) in the UI. The number of hours to wait before an artifact is deemed 'unused' and eligible for cleanup from the repository. A value of 0 means automatic cleanup of cached artifacts is disabled.
	UnusedArtifactsCleanupPeriodHours *float64 `json:"unusedArtifactsCleanupPeriodHours,omitempty" tf:"unused_artifacts_cleanup_period_hours,omitempty"`

	Username *string `json:"username,omitempty" tf:"username,omitempty"`

	// Enable Indexing In Xray. Repository will be indexed with the default retention period. You will be able to change it via Xray settings.
	XrayIndex *bool `json:"xrayIndex,omitempty" tf:"xray_index,omitempty"`
}

type RemoteNpmRepositoryObservation struct {

	// 'Lenient Host Authentication' in the UI. Allow credentials of this repository to be used on requests redirected to any other host.
	AllowAnyHostAuth *bool `json:"allowAnyHostAuth,omitempty" tf:"allow_any_host_auth,omitempty"`

	// When set, you may view content such as HTML or Javadoc files directly from Artifactory.
	// This may not be safe and therefore requires strict content moderation to prevent malicious users from uploading content that may compromise security (e.g., cross-site scripting attacks).
	ArchiveBrowsingEnabled *bool `json:"archiveBrowsingEnabled,omitempty" tf:"archive_browsing_enabled,omitempty"`

	// The number of seconds the repository stays in assumed offline state after a connection error. At the end of this time, an online check is attempted in order to reset the offline status. A value of 0 means the repository is never assumed offline.
	AssumedOfflinePeriodSecs *float64 `json:"assumedOfflinePeriodSecs,omitempty" tf:"assumed_offline_period_secs,omitempty"`

	// (A.K.A 'Ignore Repository' on the UI) When set, the repository or its local cache do not participate in artifact resolution.
	BlackedOut *bool `json:"blackedOut,omitempty" tf:"blacked_out,omitempty"`

	// If set, artifacts will fail to download if a mismatch is detected between requested and received mimetype, according to the list specified in the system properties file under blockedMismatchingMimeTypes. You can override by adding mimetypes to the override list 'mismatching_mime_types_override_list'.
	BlockMismatchingMimeTypes *bool `json:"blockMismatchingMimeTypes,omitempty" tf:"block_mismatching_mime_types,omitempty"`

	// Before caching an artifact, Artifactory first sends a HEAD request to the remote resource. In some remote resources, HEAD requests are disallowed and therefore rejected, even though downloading the artifact is allowed. When checked, Artifactory will bypass the HEAD request and cache the artifact directly using a GET request.
	BypassHeadRequests *bool `json:"bypassHeadRequests,omitempty" tf:"bypass_head_requests,omitempty"`

	// When set, download requests to this repository will redirect the client to download the artifact directly from AWS CloudFront. Available in Enterprise+ and Edge licenses only. Default value is 'false'
	CdnRedirect *bool `json:"cdnRedirect,omitempty" tf:"cdn_redirect,omitempty"`

	// Client TLS certificate name.
	ClientTLSCertificate *string `json:"clientTlsCertificate,omitempty" tf:"client_tls_certificate,omitempty"`

	ContentSynchronisation []ContentSynchronisationObservation `json:"contentSynchronisation,omitempty" tf:"content_synchronisation,omitempty"`

	// Enable repository to be protected by the Curation service.
	Curated *bool `json:"curated,omitempty" tf:"curated,omitempty"`

	// Public description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// When set to `true`, the proxy is disabled, and not returned in the API response body. If there is a default proxy set for the Artifactory instance, it will be ignored, too. Introduced since Artifactory 7.41.7.
	DisableProxy *bool `json:"disableProxy,omitempty" tf:"disable_proxy,omitempty"`

	// Whether to disable URL normalization, default is `false`.
	DisableURLNormalization *bool `json:"disableUrlNormalization,omitempty" tf:"disable_url_normalization,omitempty"`

	// When set, download requests to this repository will redirect the client to download the artifact directly from the cloud storage provider. Available in Enterprise+ and Edge licenses only. Default value is 'false'.
	DownloadDirect *bool `json:"downloadDirect,omitempty" tf:"download_direct,omitempty"`

	// Enables cookie management if the remote repository uses cookies to manage client state.
	EnableCookieManagement *bool `json:"enableCookieManagement,omitempty" tf:"enable_cookie_management,omitempty"`

	// List of artifact patterns to exclude when evaluating artifact requests, in the form of `x/y/**/z/*`.By default no artifacts are excluded.
	ExcludesPattern *string `json:"excludesPattern,omitempty" tf:"excludes_pattern,omitempty"`

	// When set, Artifactory will return an error to the client that causes the build to fail if there is a failure to communicate with this repository.
	HardFail *bool `json:"hardFail,omitempty" tf:"hard_fail,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// List of comma-separated artifact patterns to include when evaluating artifact requests in the form of `x/y/**/z/*`. When used, only artifacts matching one of the include patterns are served. By default, all artifacts are included (`**/*`).
	IncludesPattern *string `json:"includesPattern,omitempty" tf:"includes_pattern,omitempty"`

	// Lists the items of remote folders in simple and list browsing. The remote content is cached according to the value of the 'Retrieval Cache Period'. Default value is 'false'. This field exists in the API but not in the UI.
	ListRemoteFolderItems *bool `json:"listRemoteFolderItems,omitempty" tf:"list_remote_folder_items,omitempty"`

	// The local address to be used when creating connections. Useful for specifying the interface to use on systems with multiple network interfaces.
	LocalAddress *string `json:"localAddress,omitempty" tf:"local_address,omitempty"`

	// Metadata Retrieval Cache Timeout (Sec) in the UI.This value refers to the number of seconds to wait for retrieval from the remote before serving locally cached artifact or fail the request.
	MetadataRetrievalTimeoutSecs *float64 `json:"metadataRetrievalTimeoutSecs,omitempty" tf:"metadata_retrieval_timeout_secs,omitempty"`

	// The set of mime types that should override the block_mismatching_mime_types setting. Eg: 'application/json,application/xml'. Default value is empty.
	MismatchingMimeTypesOverrideList *string `json:"mismatchingMimeTypesOverrideList,omitempty" tf:"mismatching_mime_types_override_list,omitempty"`

	// Missed Retrieval Cache Period (Sec) in the UI. The number of seconds to cache artifact retrieval misses (artifact not found). A value of 0 indicates no caching.
	MissedCachePeriodSeconds *float64 `json:"missedCachePeriodSeconds,omitempty" tf:"missed_cache_period_seconds,omitempty"`

	// Internal description.
	Notes *string `json:"notes,omitempty" tf:"notes,omitempty"`

	// If set, Artifactory does not try to fetch remote artifacts. Only locally-cached artifacts are retrieved.
	Offline *bool `json:"offline,omitempty" tf:"offline,omitempty"`

	PackageType *string `json:"packageType,omitempty" tf:"package_type,omitempty"`

	// Setting Priority Resolution takes precedence over the resolution order when resolving virtual repositories. Setting repositories with priority will cause metadata to be merged only from repositories set with a priority. If a package is not found in those repositories, Artifactory will merge from repositories marked as non-priority.
	PriorityResolution *bool `json:"priorityResolution,omitempty" tf:"priority_resolution,omitempty"`

	// Project environment for assigning this repository to. Allow values: "DEV", "PROD", or one of custom environment. Before Artifactory 7.53.1, up to 2 values ("DEV" and "PROD") are allowed. From 7.53.1 onward, only one value is allowed. The attribute should only be used if the repository is already assigned to the existing project.
	// +listType=set
	ProjectEnvironments []*string `json:"projectEnvironments,omitempty" tf:"project_environments,omitempty"`

	// Project key for assigning this repository to. Must be 2 - 32 lowercase alphanumeric and hyphen characters. When assigning repository to a project, repository key must be prefixed with project key, separated by a dash.
	ProjectKey *string `json:"projectKey,omitempty" tf:"project_key,omitempty"`

	// List of property set names
	// +listType=set
	PropertySets []*string `json:"propertySets,omitempty" tf:"property_sets,omitempty"`

	// Proxy key from Artifactory Proxies settings. Can't be set if `disable_proxy = true`.
	Proxy *string `json:"proxy,omitempty" tf:"proxy,omitempty"`

	// Custom HTTP query parameters that will be automatically included in all remote resource requests. For example: `param1=val1&param2=val2&param3=val3`
	QueryParams *string `json:"queryParams,omitempty" tf:"query_params,omitempty"`

	// Repository layout key for the remote layout mapping. Repository can be created without this attribute (or set to an empty string). Once it's set, it can't be removed by passing an empty string or removing the attribute, that will be ignored by the Artifactory API. UI shows an error message, if the user tries to remove the value.
	RemoteRepoLayoutRef *string `json:"remoteRepoLayoutRef,omitempty" tf:"remote_repo_layout_ref,omitempty"`

	// Repository layout key for the remote repository
	RepoLayoutRef *string `json:"repoLayoutRef,omitempty" tf:"repo_layout_ref,omitempty"`

	// Metadata Retrieval Cache Period (Sec) in the UI. This value refers to the number of seconds to cache metadata files before checking for newer versions on remote server. A value of 0 indicates no caching.
	RetrievalCachePeriodSeconds *float64 `json:"retrievalCachePeriodSeconds,omitempty" tf:"retrieval_cache_period_seconds,omitempty"`

	ShareConfiguration *bool `json:"shareConfiguration,omitempty" tf:"share_configuration,omitempty"`

	// Network timeout (in ms) to use when establishing a connection and for unanswered requests. Timing out on a network operation is considered a retrieval failure.
	SocketTimeoutMillis *float64 `json:"socketTimeoutMillis,omitempty" tf:"socket_timeout_millis,omitempty"`

	// When set, the repository should store cached artifacts locally. When not set, artifacts are not stored locally, and direct repository-to-client streaming is used. This can be useful for multi-server setups over a high-speed LAN, with one Artifactory caching certain data on central storage, and streaming it directly to satellite pass-though Artifactory servers.
	StoreArtifactsLocally *bool `json:"storeArtifactsLocally,omitempty" tf:"store_artifacts_locally,omitempty"`

	// When set, remote artifacts are fetched along with their properties.
	SynchronizeProperties *bool `json:"synchronizeProperties,omitempty" tf:"synchronize_properties,omitempty"`

	// This is a URL to the remote registry. Consider using HTTPS to ensure a secure connection.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// Unused Artifacts Cleanup Period (Hr) in the UI. The number of hours to wait before an artifact is deemed 'unused' and eligible for cleanup from the repository. A value of 0 means automatic cleanup of cached artifacts is disabled.
	UnusedArtifactsCleanupPeriodHours *float64 `json:"unusedArtifactsCleanupPeriodHours,omitempty" tf:"unused_artifacts_cleanup_period_hours,omitempty"`

	Username *string `json:"username,omitempty" tf:"username,omitempty"`

	// Enable Indexing In Xray. Repository will be indexed with the default retention period. You will be able to change it via Xray settings.
	XrayIndex *bool `json:"xrayIndex,omitempty" tf:"xray_index,omitempty"`
}

type RemoteNpmRepositoryParameters struct {

	// 'Lenient Host Authentication' in the UI. Allow credentials of this repository to be used on requests redirected to any other host.
	// +kubebuilder:validation:Optional
	AllowAnyHostAuth *bool `json:"allowAnyHostAuth,omitempty" tf:"allow_any_host_auth,omitempty"`

	// When set, you may view content such as HTML or Javadoc files directly from Artifactory.
	// This may not be safe and therefore requires strict content moderation to prevent malicious users from uploading content that may compromise security (e.g., cross-site scripting attacks).
	// +kubebuilder:validation:Optional
	ArchiveBrowsingEnabled *bool `json:"archiveBrowsingEnabled,omitempty" tf:"archive_browsing_enabled,omitempty"`

	// The number of seconds the repository stays in assumed offline state after a connection error. At the end of this time, an online check is attempted in order to reset the offline status. A value of 0 means the repository is never assumed offline.
	// +kubebuilder:validation:Optional
	AssumedOfflinePeriodSecs *float64 `json:"assumedOfflinePeriodSecs,omitempty" tf:"assumed_offline_period_secs,omitempty"`

	// (A.K.A 'Ignore Repository' on the UI) When set, the repository or its local cache do not participate in artifact resolution.
	// +kubebuilder:validation:Optional
	BlackedOut *bool `json:"blackedOut,omitempty" tf:"blacked_out,omitempty"`

	// If set, artifacts will fail to download if a mismatch is detected between requested and received mimetype, according to the list specified in the system properties file under blockedMismatchingMimeTypes. You can override by adding mimetypes to the override list 'mismatching_mime_types_override_list'.
	// +kubebuilder:validation:Optional
	BlockMismatchingMimeTypes *bool `json:"blockMismatchingMimeTypes,omitempty" tf:"block_mismatching_mime_types,omitempty"`

	// Before caching an artifact, Artifactory first sends a HEAD request to the remote resource. In some remote resources, HEAD requests are disallowed and therefore rejected, even though downloading the artifact is allowed. When checked, Artifactory will bypass the HEAD request and cache the artifact directly using a GET request.
	// +kubebuilder:validation:Optional
	BypassHeadRequests *bool `json:"bypassHeadRequests,omitempty" tf:"bypass_head_requests,omitempty"`

	// When set, download requests to this repository will redirect the client to download the artifact directly from AWS CloudFront. Available in Enterprise+ and Edge licenses only. Default value is 'false'
	// +kubebuilder:validation:Optional
	CdnRedirect *bool `json:"cdnRedirect,omitempty" tf:"cdn_redirect,omitempty"`

	// Client TLS certificate name.
	// +kubebuilder:validation:Optional
	ClientTLSCertificate *string `json:"clientTlsCertificate,omitempty" tf:"client_tls_certificate,omitempty"`

	// +kubebuilder:validation:Optional
	ContentSynchronisation []ContentSynchronisationParameters `json:"contentSynchronisation,omitempty" tf:"content_synchronisation,omitempty"`

	// Enable repository to be protected by the Curation service.
	// +kubebuilder:validation:Optional
	Curated *bool `json:"curated,omitempty" tf:"curated,omitempty"`

	// Public description.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// When set to `true`, the proxy is disabled, and not returned in the API response body. If there is a default proxy set for the Artifactory instance, it will be ignored, too. Introduced since Artifactory 7.41.7.
	// +kubebuilder:validation:Optional
	DisableProxy *bool `json:"disableProxy,omitempty" tf:"disable_proxy,omitempty"`

	// Whether to disable URL normalization, default is `false`.
	// +kubebuilder:validation:Optional
	DisableURLNormalization *bool `json:"disableUrlNormalization,omitempty" tf:"disable_url_normalization,omitempty"`

	// When set, download requests to this repository will redirect the client to download the artifact directly from the cloud storage provider. Available in Enterprise+ and Edge licenses only. Default value is 'false'.
	// +kubebuilder:validation:Optional
	DownloadDirect *bool `json:"downloadDirect,omitempty" tf:"download_direct,omitempty"`

	// Enables cookie management if the remote repository uses cookies to manage client state.
	// +kubebuilder:validation:Optional
	EnableCookieManagement *bool `json:"enableCookieManagement,omitempty" tf:"enable_cookie_management,omitempty"`

	// List of artifact patterns to exclude when evaluating artifact requests, in the form of `x/y/**/z/*`.By default no artifacts are excluded.
	// +kubebuilder:validation:Optional
	ExcludesPattern *string `json:"excludesPattern,omitempty" tf:"excludes_pattern,omitempty"`

	// When set, Artifactory will return an error to the client that causes the build to fail if there is a failure to communicate with this repository.
	// +kubebuilder:validation:Optional
	HardFail *bool `json:"hardFail,omitempty" tf:"hard_fail,omitempty"`

	// List of comma-separated artifact patterns to include when evaluating artifact requests in the form of `x/y/**/z/*`. When used, only artifacts matching one of the include patterns are served. By default, all artifacts are included (`**/*`).
	// +kubebuilder:validation:Optional
	IncludesPattern *string `json:"includesPattern,omitempty" tf:"includes_pattern,omitempty"`

	// Lists the items of remote folders in simple and list browsing. The remote content is cached according to the value of the 'Retrieval Cache Period'. Default value is 'false'. This field exists in the API but not in the UI.
	// +kubebuilder:validation:Optional
	ListRemoteFolderItems *bool `json:"listRemoteFolderItems,omitempty" tf:"list_remote_folder_items,omitempty"`

	// The local address to be used when creating connections. Useful for specifying the interface to use on systems with multiple network interfaces.
	// +kubebuilder:validation:Optional
	LocalAddress *string `json:"localAddress,omitempty" tf:"local_address,omitempty"`

	// Metadata Retrieval Cache Timeout (Sec) in the UI.This value refers to the number of seconds to wait for retrieval from the remote before serving locally cached artifact or fail the request.
	// +kubebuilder:validation:Optional
	MetadataRetrievalTimeoutSecs *float64 `json:"metadataRetrievalTimeoutSecs,omitempty" tf:"metadata_retrieval_timeout_secs,omitempty"`

	// The set of mime types that should override the block_mismatching_mime_types setting. Eg: 'application/json,application/xml'. Default value is empty.
	// +kubebuilder:validation:Optional
	MismatchingMimeTypesOverrideList *string `json:"mismatchingMimeTypesOverrideList,omitempty" tf:"mismatching_mime_types_override_list,omitempty"`

	// Missed Retrieval Cache Period (Sec) in the UI. The number of seconds to cache artifact retrieval misses (artifact not found). A value of 0 indicates no caching.
	// +kubebuilder:validation:Optional
	MissedCachePeriodSeconds *float64 `json:"missedCachePeriodSeconds,omitempty" tf:"missed_cache_period_seconds,omitempty"`

	// Internal description.
	// +kubebuilder:validation:Optional
	Notes *string `json:"notes,omitempty" tf:"notes,omitempty"`

	// If set, Artifactory does not try to fetch remote artifacts. Only locally-cached artifacts are retrieved.
	// +kubebuilder:validation:Optional
	Offline *bool `json:"offline,omitempty" tf:"offline,omitempty"`

	// +kubebuilder:validation:Optional
	PasswordSecretRef *v1.SecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// Setting Priority Resolution takes precedence over the resolution order when resolving virtual repositories. Setting repositories with priority will cause metadata to be merged only from repositories set with a priority. If a package is not found in those repositories, Artifactory will merge from repositories marked as non-priority.
	// +kubebuilder:validation:Optional
	PriorityResolution *bool `json:"priorityResolution,omitempty" tf:"priority_resolution,omitempty"`

	// Project environment for assigning this repository to. Allow values: "DEV", "PROD", or one of custom environment. Before Artifactory 7.53.1, up to 2 values ("DEV" and "PROD") are allowed. From 7.53.1 onward, only one value is allowed. The attribute should only be used if the repository is already assigned to the existing project.
	// +kubebuilder:validation:Optional
	// +listType=set
	ProjectEnvironments []*string `json:"projectEnvironments,omitempty" tf:"project_environments,omitempty"`

	// Project key for assigning this repository to. Must be 2 - 32 lowercase alphanumeric and hyphen characters. When assigning repository to a project, repository key must be prefixed with project key, separated by a dash.
	// +kubebuilder:validation:Optional
	ProjectKey *string `json:"projectKey,omitempty" tf:"project_key,omitempty"`

	// List of property set names
	// +kubebuilder:validation:Optional
	// +listType=set
	PropertySets []*string `json:"propertySets,omitempty" tf:"property_sets,omitempty"`

	// Proxy key from Artifactory Proxies settings. Can't be set if `disable_proxy = true`.
	// +kubebuilder:validation:Optional
	Proxy *string `json:"proxy,omitempty" tf:"proxy,omitempty"`

	// Custom HTTP query parameters that will be automatically included in all remote resource requests. For example: `param1=val1&param2=val2&param3=val3`
	// +kubebuilder:validation:Optional
	QueryParams *string `json:"queryParams,omitempty" tf:"query_params,omitempty"`

	// Repository layout key for the remote layout mapping. Repository can be created without this attribute (or set to an empty string). Once it's set, it can't be removed by passing an empty string or removing the attribute, that will be ignored by the Artifactory API. UI shows an error message, if the user tries to remove the value.
	// +kubebuilder:validation:Optional
	RemoteRepoLayoutRef *string `json:"remoteRepoLayoutRef,omitempty" tf:"remote_repo_layout_ref,omitempty"`

	// Repository layout key for the remote repository
	// +kubebuilder:validation:Optional
	RepoLayoutRef *string `json:"repoLayoutRef,omitempty" tf:"repo_layout_ref,omitempty"`

	// Metadata Retrieval Cache Period (Sec) in the UI. This value refers to the number of seconds to cache metadata files before checking for newer versions on remote server. A value of 0 indicates no caching.
	// +kubebuilder:validation:Optional
	RetrievalCachePeriodSeconds *float64 `json:"retrievalCachePeriodSeconds,omitempty" tf:"retrieval_cache_period_seconds,omitempty"`

	// +kubebuilder:validation:Optional
	ShareConfiguration *bool `json:"shareConfiguration,omitempty" tf:"share_configuration,omitempty"`

	// Network timeout (in ms) to use when establishing a connection and for unanswered requests. Timing out on a network operation is considered a retrieval failure.
	// +kubebuilder:validation:Optional
	SocketTimeoutMillis *float64 `json:"socketTimeoutMillis,omitempty" tf:"socket_timeout_millis,omitempty"`

	// When set, the repository should store cached artifacts locally. When not set, artifacts are not stored locally, and direct repository-to-client streaming is used. This can be useful for multi-server setups over a high-speed LAN, with one Artifactory caching certain data on central storage, and streaming it directly to satellite pass-though Artifactory servers.
	// +kubebuilder:validation:Optional
	StoreArtifactsLocally *bool `json:"storeArtifactsLocally,omitempty" tf:"store_artifacts_locally,omitempty"`

	// When set, remote artifacts are fetched along with their properties.
	// +kubebuilder:validation:Optional
	SynchronizeProperties *bool `json:"synchronizeProperties,omitempty" tf:"synchronize_properties,omitempty"`

	// This is a URL to the remote registry. Consider using HTTPS to ensure a secure connection.
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// Unused Artifacts Cleanup Period (Hr) in the UI. The number of hours to wait before an artifact is deemed 'unused' and eligible for cleanup from the repository. A value of 0 means automatic cleanup of cached artifacts is disabled.
	// +kubebuilder:validation:Optional
	UnusedArtifactsCleanupPeriodHours *float64 `json:"unusedArtifactsCleanupPeriodHours,omitempty" tf:"unused_artifacts_cleanup_period_hours,omitempty"`

	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`

	// Enable Indexing In Xray. Repository will be indexed with the default retention period. You will be able to change it via Xray settings.
	// +kubebuilder:validation:Optional
	XrayIndex *bool `json:"xrayIndex,omitempty" tf:"xray_index,omitempty"`
}

// RemoteNpmRepositorySpec defines the desired state of RemoteNpmRepository
type RemoteNpmRepositorySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     RemoteNpmRepositoryParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RemoteNpmRepositoryInitParameters `json:"initProvider,omitempty"`
}

// RemoteNpmRepositoryStatus defines the observed state of RemoteNpmRepository.
type RemoteNpmRepositoryStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RemoteNpmRepositoryObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RemoteNpmRepository is the Schema for the RemoteNpmRepositorys API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,artfactory}
type RemoteNpmRepository struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              RemoteNpmRepositorySpec   `json:"spec"`
	Status            RemoteNpmRepositoryStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RemoteNpmRepositoryList contains a list of RemoteNpmRepositorys
type RemoteNpmRepositoryList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RemoteNpmRepository `json:"items"`
}

// Repository type metadata.
var (
	RemoteNpmRepository_Kind             = "RemoteNpmRepository"
	RemoteNpmRepository_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RemoteNpmRepository_Kind}.String()
	RemoteNpmRepository_KindAPIVersion   = RemoteNpmRepository_Kind + "." + CRDGroupVersion.String()
	RemoteNpmRepository_GroupVersionKind = CRDGroupVersion.WithKind(RemoteNpmRepository_Kind)
)

func init() {
	SchemeBuilder.Register(&RemoteNpmRepository{}, &RemoteNpmRepositoryList{})
}
