apiVersion: batch/v1
kind: Job
metadata:
  name: create-credentials
spec:
  template:
    spec:
      containers:
      - name: main
        image: alpine:latest
        env:
        - name: ARTIFACTORY_URL
          valueFrom:
            secretKeyRef:
              name: artifactory-creds
              key: ARTIFACTORY_URL
        - name: ARTIFACTORY_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: artifactory-creds
              key: ARTIFACTORY_ACCESS_TOKEN
        command:
          - /bin/sh
          - -c
          - |
            #!/bin/sh
            set -e
            echo "Updating package index..."
            apk update
            echo "Installing kubectl, curl, and jq..."
            apk add --no-cache curl jq
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x kubectl
            mv kubectl /usr/local/bin/

            ### CREATE CREDENTIALS ###
            mkdir /work
            kubectl delete secret artifactory-credentials || true
            ARTIFACTORY_URL=$(kubectl get secret artifactory-creds -o jsonpath="{.data.ARTIFACTORY_URL}" | base64 --decode)
            ARTIFACTORY_ACCESS_TOKEN=$(kubectl get secret artifactory-creds -o jsonpath="{.data.ARTIFACTORY_ACCESS_TOKEN}" | base64 --decode)
            echo "{access_token: $ARTIFACTORY_ACCESS_TOKEN, url: $ARTIFACTORY_URL}" > /work/creds.json
            kubectl create secret generic artifactory-credentials --from-file=/work/creds.json
      restartPolicy: Never
      serviceAccountName: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: create-credentials
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-credentials
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: create-credentials
  apiGroup: rbac.authorization.k8s.io
