apiVersion: jfrogartifactory.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: my-artifactory-providerconfig
spec:
  credentials:
    source: Secret
    secretRef:
      name: artifactory-credentials
      namespace: default
      key: creds.json
